### ISSUE TITLE
MVC6 Setup

### ISSUE THREAD

**Issue by ChrisFelstead** [brentj73/ControllerLess#5]
I'm trying to get this working with MVC6, however, it's serving blank pages. I don't think the route handlers is being used. Please advise.

**Comment by brentj73** [comment]
I haven't tried it in MVC6 yet but there have been some fundamental changes to the way routing works compared with how it works in MVC5.

There is some useful information at http://www.ryadel.com/en/custom-routing-method-names-in-asp-net-5-mvc-6/ which may provide a clue to how ControlleLess can be used with MVC6 (in particular the section titled Convention-Based Approach).

I'll need to set up a sample MVC6 project and give it a try to see if it works.

**Comment by brentj73** [comment]
Development note: Another useful overview of MVC6 routing is http://stephenwalther.com/archive/2015/02/07/asp-net-5-deep-dive-routing

**Comment by ChrisFelstead** [comment]
Thanks Brent, I've read this. I've come up with a solution but there is a problem with static files until they implement the ability to ignore routes again.

**Comment by brentj73** [comment]
Hi Chris. Would it be possible to take a look at your solution? Do you have the `app.UseStaticFiles();` statement in your `Configure(...)` method? Thanks.

**Comment by ChrisFelstead** [comment]
I do. 

`public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();

            if (env.IsDevelopment())
            {
                app.UseBrowserLink();
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }

            app.UseIISPlatformHandler();

            app.UseStaticFiles();
            app.UseDefaultFiles();
            //app.UseMiddleware<ServerFileMiddleware>();

            app.UseMvc(routes =>
            {
                //routes.MapRoute(
                //    name: "default",
                //    template: "{controller=Home}/{action=Index}/{id?}");

                routes.MapRoute("Wildcard Routing",
                        "{*anything}",
                        new { controller = "Wildcard", action = "Get" },
                        new { anything = @"^(.*)?$" });
            });
        }`

**Comment by brentj73** [comment]
Thanks for the information. Let me take a look and see what I can do. My gut feeling is that we might need a new version of the ControllerLess code for ASP.NET 5 because of the changes in the way routing and controllers work. 

The current ControllerLess code inherits from the System.Web.Mvc.Controller class which probably isn't correct for ASP.NET 5- I think it should probably be inheriting from Microsoft.AspNet.Mvc.Controller instead.

**Comment by brentj73** [comment]
Just following up on this, I've finally had some time to take a closer look at ASP.NET 5/MVC6 and it looks like the routing mechanism has been overhauled. Additionally, as it's still at RC stage there isn't a great deal of documentation about how to hook into the routing of requests.

I'll leave this for now until ASP.NET 5 is released and more information is made available. This will be a new project to port this across to MVC6.
