### ISSUE TITLE
Requests for missing views return 500 error

### ISSUE THREAD

**Issue by keywest1** [brentj73/ControllerLess#6]
In a new default MVC 4 project, requests for non-existent views will return a 404 error.

However, with ControllerLess in place, requests for non-existent views return a 500 error, not a 404.

An unhandled InvalidOperationException is raised by ControllerLessHttpHander.DispatchRequest() when it hits viewController.Execute(_requestContext).

(I have enabled Area support per the ControllerLess wiki.)

**Comment by brentj73** [comment]
Hi,

I've added a 404 response to the ControllerLessHttpHandler class when a view cannot be found for a specific route in 26cffe1. All other exception types should continue to pass through unhandled.

I'll update the NuGet package for this project shortly.

Thanks!

**Comment by keywest1** [comment]
Thanks Brent! The update looks pretty straightforward. ☺ I’ll give it a try.  JBC

**Comment by brentj73** [comment]
No problem. The NuGet package is now available over at https://www.nuget.org/packages/ControllerLess/1.0.9

Thanks
Brent
